on:
  schedule:
    - cron:  '0 * * * *' # Every hour. Ref https://crontab.guru/examples.html
  push:
    branches:
      - master

name: Scrape Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: apt-get build-dep python3-lxml -y && pip install lxml scrape 
    - name: Scrape data
      run: python scrape.py
    - uses: stefanzweifel/git-auto-commit-action@v4
