on:
  schedule:
    - cron:  '0 * * * *' # Every hour. Ref https://crontab.guru/examples.html
  push:
    branches:
      - master

name: Scrape Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libxml2-dev libxslt-dev python2-dev python2 python-dev-is-python3
    - name: Install packages
      run: pip install parse lxml pandas seaborn tabulate -U
    - name: Scrape data
      run: python scrape.py
    - name: Update graph
      run: python graph.py
    - uses: stefanzweifel/git-auto-commit-action@v4
